query_display: true
query_sort: 1
execution: 5
api_url: api.drupal.org
timer: 1
memory: 1
redirect_page: 0
page_alter: false
raw_names: false
error_handlers:
  - '0'
  - '1'
krumo_skin: default
rebuild_theme: false
use_uncompressed_jquery: false
debug_mail_file_format: '%to-%subject-%datetime.mail.txt'
debug_mail_directory: 'temporary://devel-mails'
